### PR TITLE
0.9.0 Release

### PR DESCRIPTION
**Pull request by ndolhii**
In this PR I updated the copyright headers and changes the year to `2023`.

Also, I updated the description of the `env` input variable to clarify how this setting will affect different images.

This release is going to be published as `0.9.0` to make it the same as the latest release of the [Liquor](https://github.com/SpineEventEngine/message-delivery) server.

### CODE REVIEW

**Comment by nick-dolgiy** [comment]
@armiol PTAL.

**Review by armiol — CHANGES_REQUESTED** [review]
@nick-dolgiy as discussed, let's document the available parameters in  the root-level `README.md`.

**Comment by nick-dolgiy** [comment]
@armiol PTAL.

**Review by armiol — APPROVED** [review]
@nick-dolgiy LGTM with a single comment to address.

**Pull request merged**
